#!/bin/sh 

echo "Deleting GNUmakefiles."
echo "Starting at root $1"

TARGETS=`find $1 -name GNUmakefile`
for item in $TARGETS
do
    echo "Item = $item"
    target=`echo $item | sed "s/ /\ /"`
    echo "Deleting $target"
    rm -r -- "$target"
done

TARGETS=`find $1 -name *.mak`
for item in $TARGETS
do
    echo "Item = $item"
    target=`echo $item | sed "s/ /\ /"`
    echo "Deleting $target"
    rm -r -- "$target"
done

echo "Finished."
