#!/bin/sh 

echo "Deleting Left-Over Static Libraries"
echo "Starting at root $1"

TARGETS=`find $1 -name *.a`
for item in $TARGETS
do
    echo "Item = $item"
    target=`echo $item | sed "s/ /\ /"`
    echo "Deleting $target"
    rm -r -- "$target"
done

echo "Finished."
