.\" @(#)gen-makefile.1		-*- nroff -*-
.TH gen-makefile 1 "03 March 2001" "Gwydion Dylan" "Gwydion Dylan"
.UC
.SH NAME
gen-makefile \- Dylan Makefile Utility
.SH SYNOPSIS
.B gen-makefile
.RB "[\|" \-pplatforms.descr "\|]"
.I dir\c
\|]
.SH WARNING
This man page is intended to supplement the main Gwydion Dylan
documentation at
.IR http://www.gwydiondylan.org/ .
It provides an incomplete reference of the available options. For a full
reference or a tutorial, please see the web site.
.SH DESCRIPTION
.B gen-makefile
turns a single Makegen file into a Makefile.
.B gen-makefile
does the bulk of the work for mk-build-tree(1), which calls
.B gen-makefile
once for each Makegen file in the tree.

This tool is really only useful for building the Gwydion Dylan compiler
set, but is provided in case users wish to package their own Dylan programs
as source code with a known building infrastructure.
.SH SEE ALSO
mk-build-tree(1), dylan(7), gwydion(7).
.PP
Much more extensive documentation in various formats is available through
the Gwydion Dylan web site at
.IR http://www.gwydiondylan.org/ .
.SH AUTHORS
The Gwydion Group at CMU and the current Gwydion Dylan maintainers. See the
CREDITS file in the Gwydion Dylan distribution for more information.

