.\" @(#)make-dylan-lib.1		-*- nroff -*-
.TH make-dylan-lib 1 "03 March 2001" "Gwydion Dylan" "Gwydion Dylan"
.UC
.SH NAME
make-dylan-lib \- Dylan Makefile Utility
.SH SYNOPSIS
.B make-dylan-lib
.I libname\c
\|]
.SH WARNING
This man page is intended to supplement the main Gwydion Dylan
documentation at
.IR http://www.gwydiondylan.org/ .
It provides an incomplete reference of the available options. For a full
reference or a tutorial, please see the web site.
.SH DESCRIPTION
.B make-dylan-lib
creates a skeleton build directory for a Dylan project.  If you supply it the
name of a library, 
.B make-dylan-lib
will do the work of creating a sample implementation file, library
interface definition (LID) file, an exports file, and a simple Makefile.
You can then edit these files and then use make(1) to compile and test
your work.

.SH SEE ALSO
dylan(7), d2c(1), dybug(1), make(1), gwydion(7).
.PP
Much more extensive documentation in various formats is available through
the Gwydion Dylan web site at
.IR http://www.gwydiondylan.org/ .
.SH AUTHORS
The Gwydion Group at CMU and the current Gwydion Dylan maintainers. See the
CREDITS file in the Gwydion Dylan distribution for more information.

