.\" @(#)mindycomp.1		-*- nroff -*-
.TH mindyexec 1 "03 March 2001" "Gwydion Dylan" "Gwydion Dylan"
.UC
.SH NAME
mindyexec \- A Dylan Batch Bytecode Interpreter
.SH SYNOPSIS
.B mindyexec
.I input-file\c
.SH WARNING
This man page is intended to supplement the main Gwydion Dylan
documentation at
.IR http://www.gwydiondylan.org/ .
It provides an incomplete reference of the available options. For a full
reference or a tutorial, please see the web site.
.SH DESCRIPTION
.B mindyexec
is a batch interpreter for the Mindy Dylan interpreter.  It accepts a subset
of the full Dylan language, and accepts a bytecode file (previously produced
by mindycomp(1).

.SH SEE ALSO
mindy(1), mindycomp(1), dylan(7), gwydion(7).
.PP
Much more extensive documentation in various formats is available through
the Gwydion Dylan web site at
.IR http://www.gwydiondylan.org/ .
.SH AUTHORS
The Gwydion Group at CMU and the current Gwydion Dylan maintainers. See the
CREDITS file in the Gwydion Dylan distribution for more information.

