Module: main
Note: this file is generated by Rob Myers, not gen-makefile from Makegen

define constant $default-dylan-dir = "";		// default_DYLANDIR || destdir
define constant $default-dylan-user-dir = "";	// sitelibdirprefix
define constant $default-target-name = #"MacOS-ppc";